### ISSUE TITLE
Set iteration not supported when compiling to ES5

### ISSUE THREAD

**Issue by gedeck** [aclarkxyz/web_molkit#4]
In order to run the code on IE11, it must be compiled to ES5. Iterating over sets is not supported in this case. It is therefore necessary to convert the `Set` first to an Array using `Array.from(set)`. 

Line 239 in `BayesianModels.ts` needs to be changed:
```
		// double duty: use the same source material to add up the numeric predictor as well (note that the "coverage" hashes are not necessarily
		// the same as the approved list)
		let pred = 0;
		for (let h of Array.from(predHashes))
		{
			let c = this.contribs[<any>h];
			if (c != null) pred += c;
		}
```

**Comment by aclarkxyz** [comment]
ES6 is the minimum target.
