### ISSUE TITLE
Errors Encountered while compiling PageOpenMol.ts

### ISSUE THREAD

**Issue by johnsantamariajr** [aclarkxyz/web_molkit#6]
<img width="884" alt="screen shot 2018-01-28 at 7 23 10 pm" src="https://user-images.githubusercontent.com/16669755/35489157-165345ac-0461-11e8-9699-c250e095e8e0.png">

Hope that's helpful! Eager to try this out, thanks,

**Comment by aclarkxyz** [comment]
You have to compile the whole project at once, not just a single file. Try changing to $BASE/demo/OpenMol and running `tsc`.
